name: Angular_CI

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build: Build and test
  runs-on: self-hosted
  steps:
    - uses: actions/checkout@v2
    - name: Use Node 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: install dependencies
      run: install npm
