name: Build and test - YARN

on:
  push:
    branches: main
  pull_request:
    branches: main
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          
      - name: install packages
        run: yarn install
      - name: check linting
        run: yarn lint
      - name: test
        run: yarn test
